FROM ubuntu:20.04

RUN apt update && apt install -y vim inetutils-ping tcpdump iproute2

# RUN ip route del default && \
#     ip route add default via 10.10.110.130

# CMD ["tail", "-f", "/dev/null"]